### ISSUE TITLE
Extension to RGBA as well as RGB

### ISSUE THREAD

**Issue by lmmx** [yinboc/liif#12]
Hi there, I've been using [LIIF on emoji glyphs](https://github.com/lmmx/emoji-liif/) and got some great results, however I'd like to recover the transparency, which I had to remove\* by simple alpha compositing (i.e. flattening the image) before passing the PNG inputs to LIIF.

> \* flattening onto a grayscale background after [calculating](https://github.com/lmmx/emoji-liif/blob/master/osx/catalina/calculate_bg.py) the grayscale tone not present in any semitransparent pixels, with greatest Euclidean distance from the median of the pixel mean in the image

I tried to "supervise" the estimation of transparency but it was only a rough estimate, and the results it gives are not satisfactory (despite the high quality obtained from LIIF)

![](https://raw.githubusercontent.com/lmmx/emoji-liif/master/SR_RGBA_reconstruction_comparison.png)

> This subsection of an emoji glyph was flattened against a black background then run through LIIF.
> The bottom right plot shows the recovered transparency (RGBA image) flattened against a different background colour (white)

I was wondering if you think the code could be modified in some way for this, to supervise an estimate of the alpha channel?

It seems like it should be possible but it's unclear to me how I might implement it, any advice would be appreciated

**Comment by yinboc** [comment]
Hi, thanks for your interest in our work! LIIF on emoji is really an interesting project.

I am not very familiar with the processing of alpha channel. Since the model is only trained for RGB images, the alpha channel will make it an out-of-distribution task. If there are a large amount of LR-HR pairs of images with alpha channel, a straight-forward method is to modify the code to work on 4-channel images (since all the code assume 3-channel, there can be many necessary modifications such as the encoder model part and the data normalization part) and train a 4-channel SR model.

**Comment by lmmx** [comment]
No problem, thanks for the response! 😄

**Comment by JerryX1110** [comment]
> No problem, thanks for the response! 😄

Have you tried this later? I am curious about the result.

**Comment by lmmx** [comment]
@JerryX1110 I am preparing a dataset of images with transparency [here](https://github.com/lmmx/wikitransp), I expect it will be ready soon, with many large images with a range of alpha values to train a network on.

I just found out there is [a recent paper](https://arxiv.org/abs/2107.08717) on joint implicit image functions “JIIF” ([code](https://github.com/ashawkey/jiif)) which modifies LIIF for the task of upsampling a low resolution depth image alongside the RGB image, which I think is comparable to the task I proposed (of upsampling an RGBA image). I’m curious to see how this goes too!
