### ISSUE TITLE
Not the result I expected

### ISSUE THREAD

**Issue by yaseryacoob** [yinboc/liif#16]
In trying super resolution on faces fr
![0](https://user-images.githubusercontent.com/8571131/110517945-830f2b00-80d9-11eb-9a02-226ad41ba205.jpg)
om CELEBHQ, I get poor results (using both pretrained models).
See the 1Kx1K output below.
![output](https://user-images.githubusercontent.com/8571131/110518022-99b58200-80d9-11eb-85ab-bd59feb9f5af.png)

**Comment by xinzi2018** [comment]
i have the same problem!

**Comment by yinboc** [comment]
It should work if you follow the instruction and generate the celebAHQ png files, the pretrained model may work better.
E.g. try this png image:
![128](https://user-images.githubusercontent.com/10364424/115099284-94184b00-9f67-11eb-9cb0-f28dc07610f2.png)

I hypothesize this is because the potential noise in your jpg file makes the input out of the training domain, as the model is trained for png files without much noise.
