### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by zpkosmos** [yinboc/liif#7]
Thanks for your excellent idea and code, these really enlighten me a lot.
There some parts of the code I don’t understand, could you please give me some guidance?

https://github.com/yinboc/liif/blob/f80be3e4fd5f1fcfbf9bbc584184e4b034e88874/models/liif.py#L82
rel_coord = coord - q_coord
rel_coord[:, :, 0] *= feat.shape[-2]
rel_coord[:, :, 1] *= feat.shape[-1]

What is the 'rel_coord' refer to?  I think the 'coord' and 'q_coord' refer to the xq and v*t in  Eq(4) in your paper, what is the 'rel_coord' refer to?  I have the same problem with 'rel_cell'. 
Looking forward for your response, thank you!

**Comment by yinboc** [comment]
That's a good point. "rel" refers to "relative", we convert the coordinate/cell-size to the relative scale before feeding into the network, that each of the feature map's grid (grid in Figure 2) has the range [-1, 1]. The motivation is that, since it is "local implicit function", we do not want x_q - v* to depend on the whole image size (without relative coordinate, the global range is fixed to be [-1, 1] and x_q - v* will be smaller if there are more pixels), thus we convert it to a local scale where we assume a feature map's grid has the range [-1, 1].
Thanks for asking this! I think we should clarify it in an updated version of the paper.

**Comment by yinboc** [comment]
That's a good point.
"rel" refers to "relative", it converts the coordinate/cell-size to a relative scale that each grid in the feature map (e.g. grids in Figure 2) has a range [-1, 1]. The motivation is that since it is "local implicit function", it needs to see things in a local scale that is invariant to the whole image size.
For example, imagine that in Figure 2 the input image is 3x3 and we want a x2 up-sampling, there should be 2x2 query pixels (x_q) in the top-left grid (let v* denote its feature vector). With relative coordinate, the x_q - v* should be (+-0.5, +-0.5) - (0, 0) = (+-0.5, +-0.5), thus the implicit function learns to up-sample at locations (+-0.5, +-0.5) for the x2-task. However, if we use a global coordinate, x_q - v* will depend on the whole image size (since the global range is fixed to be [-1, 1]), the implicit function will receive inconsistent values of x_q - v* for the x2-task, thus things are not working correctly.

Thanks for asking this! We will clarify it in an updated version of the paper.

**Comment by zpkosmos** [comment]
Thank you for your reply and your easy-to-understand examples, these really helped me a lot to understand your code and paper. I originally thought that cell decoding is the only measure you use to solve the problems caused by different image sizes. The relative coordinate is really an ingenious method used to unify the LIIF of different positions of the picture under the same scale. I will be very happy to introduce your work to the students in my laboratory in detail.

**Comment by yinboc** [comment]
Thanks for your interest in our work!
I feel it may be better to keep this issue open until we update the paper.

**Comment by jikerWRN** [comment]
Hi, thanks for your great work! Would you explain why 
rel_coord[:, :, 0] *= feat.shape[-2]
rel_coord[:, :, 1] *= feat.shape[-1]
and 
rel_cell[:, :, 0] *= feat.shape[-2]
rel_cell[:, :, 1] *= feat.shape[-1]

Looking forward for your response, thank you!

**Comment by yinboc** [comment]
Assume the feature map `feat` has the shape HxW, the coordinate from global view has the range [-1, 1], the coordinate from local view should have the range [-H, H] and [-W, W], since we assume each grid has the range [-1, 1] and there are H/W grids in a column/row.

**Comment by yinboc** [comment]
Assume the feature map feat has the shape HxW, the coordinate from global view has the range [-1, 1], the coordinate from local view should have the range [-H, H] and [-W, W], since we assume each grid has the range [-1, 1] and there are H/W grids in a column/row. That is, we need to multiply the relative coordinate by a factor H or W.

**Comment by jikerWRN** [comment]
Ok, i got it, thanks again!

**Comment by codyshen0000** [comment]
so   why  vx need to be divided by feat.shape[-2]?  (note:rx = 1/ feat.shape[-2] )
https://github.com/yinboc/liif/blob/7f0ec6b1e0cac4b52858f1fa4a67d527fd47079a/models/liif.py#L70

**Comment by yinboc** [comment]
> so why vx need to be divided by feat.shape[-2]? (note:rx = 1/ feat.shape[-2] )
> https://github.com/yinboc/liif/blob/7f0ec6b1e0cac4b52858f1fa4a67d527fd47079a/models/liif.py#L70

vx is whether -1 or 1, rx is the field radius with global range [-1, 1] as noted in L57. coord_ is for finding the nearest feature vectors in 4 directions. Conversion to local relative coordinates is at L81-83.

**Comment by codyshen0000** [comment]
Thanks for your reply! By the way,  Could you share with me the origin of "Feature Unfolding" thoughts?

**Comment by yinboc** [comment]
> Thanks for your reply! By the way, Could you share with me the origin of "Feature Unfolding" thoughts?

You're welcome, its motivation is to enlarge the reception field of the local implicit function.
