### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by codyshen0000** [yinboc/liif#8]
https://github.com/yinboc/liif/blob/7f0ec6b1e0cac4b52858f1fa4a67d527fd47079a/test.py#L16
Hi, I don't quite understand the meaning of 'bsize', can you give me some guidance? 

Looking forward to your response, thank you!

**Comment by yinboc** [comment]
Hi, `bsize` denotes the batch size of points for "rendering". Let's consider that we want to output a 2048x2048 image, there will be 2048*2048=4194304 points for the neural implicit function (MLP) to query at. While inputing all of them at once may exceed the GPU memory limit, we can process by smaller batches since the pixel queries are independent.

**Comment by codyshen0000** [comment]
Got it!  Thanks again
